#!/bin/bash
list=$(sudo vzlist)
if echo $list | grep -q "HOSTNAME $1"
then
    echo "Container found"
    sudo vzctl stop $1
    sudo vzctl destroy $1
    ####
    #Modify this snapshot to the one you want to replace it with
    snapshot=/vz/dump/vzdump-openvz-100-2016_02_25-17_53_39.tar
    #snapshot=$(ls /vz/dump | grep ".tar" | grep "-$1-" | tail -n1)
    
    ####
    sudo vzrestore $snapshot $1 #container snapshot put here
    sudo vzctl start $1
    sudo brctl addif br0 "veth${1}.0"
    #commands can be run on container
    #in format sudo vzctl exec $1 [command]
else
    echo "Container not found"
fi
